In [1]:
import torch

In [3]:
x = torch.empty(1) # scalar
x

tensor([2.1715e-18])

In [4]:
x = torch.empty(3)
x

tensor([-3.2015e-23,  3.2168e-41, -2.6344e+01])

In [6]:
x = torch.empty(2,2)
x

tensor([[9.1477e-41, 0.0000e+00],
        [1.1210e-44, 0.0000e+00]])

In [7]:
x = torch.rand(5, 3)
x

tensor([[0.2536, 0.6230, 0.8168],
        [0.2067, 0.9438, 0.8640],
        [0.5843, 0.5867, 0.0265],
        [0.6702, 0.5498, 0.3732],
        [0.7246, 0.3984, 0.2653]])

In [9]:
x.size()

torch.Size([5, 3])

In [11]:
x.dtype

torch.float32

In [12]:
x = torch.tensor([5.5, 3], requires_grad=True)
x

tensor([5.5000, 3.0000], requires_grad=True)

In [19]:
# Reshape with view()
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8)

In [20]:
x.size(), y.size(), z.size()

(torch.Size([4, 4]), torch.Size([16]), torch.Size([2, 8]))